"""The only persisted local state.

`talossecrets.yaml` holds the Talos machine secrets (cluster CA, etcd CA, join
tokens); it is the cluster's cryptographic identity and CANNOT be regenerated --
losing it means losing control of the cluster. It is a critical artifact on par
with cluster.yaml and secrets.yaml, gitignored, mode 0600.

Everything else (IPs, IDs, the machines map) is re-derived live from the selected
provider, so it is not persisted here.
"""

from __future__ import annotations

import os
from pathlib import Path

from .errors import StateError
from .output import action, dry_run

SECRETS_FILE = "talossecrets.yaml"
# derived client configs: regenerated by converge from the secrets (talosconfig)
# and by `talosctl kubeconfig` (kubeconfig), so they are safe to delete
DERIVED_FILES = ("talosconfig", "kubeconfig")


def write_private(path: Path, contents: str) -> None:
    """Write text to path as mode 0600.

    Open with the mode up front (subject to umask, which only tightens) rather
    than write-then-chmod, so a fresh file is never briefly open to the world
    between creation and a chmod; fchmod still forces 0600 when the file
    already exists with a broader mode.
    """
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        os.fchmod(fd, 0o600)
    except BaseException:
        os.close(fd)
        raise
    with os.fdopen(fd, "w") as f:
        f.write(contents)


class State:
    def __init__(self, root: Path):
        self.root = root
        self.secrets_path = root / SECRETS_FILE

    # -- talos machine secrets ---------------------------------------------

    def secrets_exist(self) -> bool:
        return self.secrets_path.is_file() and self.secrets_path.stat().st_size > 0

    def write_secrets(self, contents: str) -> None:
        """Persist the raw output of `talosctl gen secrets` (mode 0600)."""
        write_private(self.secrets_path, contents)

    def require_secrets(self) -> Path:
        """Return the secrets path, or fail hard if it is missing.

        Missing secrets when a cluster already exists is unrecoverable, so this
        is a hard error -- we never silently regenerate them.
        """
        if not self.secrets_exist():
            raise StateError(
                f"{self.secrets_path} is missing. This file is the cluster's "
                "irreplaceable identity (CA + tokens). If the cluster exists, "
                "restore it from backup; it cannot be regenerated."
            )
        return self.secrets_path

    def reset(self, keep_talosconfig: bool = False) -> None:
        """Wipe local state after a destroy: delete the talos machine secrets
        and the client configs derived from them.
        A destroy destroys the cluster, so the next
        converge starts a genuinely NEW cluster with a fresh identity (new cluster
        id) -- which also prevents the discovery service from carrying stale
        affiliate records across recreates.

        talosconfig/kubeconfig go too: they carry the destroyed cluster's CA and
        credentials, so keeping them only leaves clients pointing at a cluster
        that no longer exists (and stale contexts accumulating in kubeconfig).
        Converge rewrites both. A destroy that leaves bare-metal machines behind
        keeps the talosconfig instead (keep_talosconfig=True): no provider
        removes those machines, and the operator resets each one with
        `talosctl --talosconfig talosconfig -n <node> reset` once this has run.
        """
        derived = list(DERIVED_FILES)
        if keep_talosconfig:
            derived.remove("talosconfig")
        for path in (self.secrets_path, *(self.root / f for f in derived)):
            if not path.exists():
                continue
            action(f"remove {path.name}")
            if not dry_run():
                path.unlink(missing_ok=True)
