"""The only persisted local state.

`talossecrets.yaml` holds the Talos machine secrets (cluster CA, etcd CA, join
tokens) that terraform used to keep inside terraform.tfstate. It is the cluster's
cryptographic identity and CANNOT be regenerated -- losing it means losing
control of the cluster. It is a critical artifact on par with cluster.yaml and
secrets.yaml (see README-python.md), gitignored, mode 0600.

Everything else terraform's state held (IPs, IDs, the machines map) is re-derived
live by querying OpenStack, so it is not persisted here.
"""

from __future__ import annotations

import os
from pathlib import Path

from .errors import StateError
from .output import action, dry_run

SECRETS_FILE = "talossecrets.yaml"
# derived client configs: regenerated by converge from the secrets (talosconfig)
# and by `talosctl kubeconfig` (kubeconfig), so they are safe to delete
DERIVED_FILES = ("talosconfig", "kubeconfig")


class State:
    def __init__(self, root: Path):
        self.root = root
        self.secrets_path = root / SECRETS_FILE

    # -- talos machine secrets ---------------------------------------------

    def secrets_exist(self) -> bool:
        return self.secrets_path.is_file() and self.secrets_path.stat().st_size > 0

    def write_secrets(self, contents: str) -> None:
        """Persist the raw output of `talosctl gen secrets` (mode 0600)."""
        self.secrets_path.write_text(contents)
        os.chmod(self.secrets_path, 0o600)

    def require_secrets(self) -> Path:
        """Return the secrets path, or fail hard if it is missing.

        Missing secrets when a cluster already exists is unrecoverable, so this
        is a hard error -- we never silently regenerate them.
        """
        if not self.secrets_exist():
            raise StateError(
                f"{self.secrets_path} is missing. This file is the cluster's "
                "irreplaceable identity (CA + tokens). If the cluster exists, "
                "restore it from backup; it cannot be regenerated."
            )
        return self.secrets_path

    def reset(self) -> None:
        """Wipe local state after a destroy: delete the talos machine secrets
        and the client configs derived from them.
        A destroy destroys the cluster, so the next
        converge starts a genuinely NEW cluster with a fresh identity (new cluster
        id) -- which also prevents the discovery service from carrying stale
        affiliate records across recreates.

        talosconfig/kubeconfig go too: they carry the destroyed cluster's CA and
        credentials, so keeping them only leaves clients pointing at a cluster
        that no longer exists (and stale contexts accumulating in kubeconfig).
        Converge rewrites both.
        """
        for path in (self.secrets_path, *(self.root / f for f in DERIVED_FILES)):
            if not path.exists():
                continue
            action(f"remove {path.name}")
            if not dry_run():
                path.unlink(missing_ok=True)
